version: "3.3"
services:
  challenge:
    image: chainflag/solidctf:main
    restart: unless-stopped
    ports:
      - "23000:20000"
    env_file:
      - .env
    volumes:
      - ./flag.txt:/ctf/flag.txt
      - ./contracts:/ctf/contracts
      - ./challenge.yml:/ctf/challenge.yml

  asethereum:
    image: chainflag/fogeth
    restart: unless-stopped
    container_name: asfogeth
    ports:
      - "18545:8545"
    env_file:
      - .env
    volumes:
      - ./genesis.json.template:/genesis.json.template
      - ./data:/data
      - ./logs:/var/log/nginx

  asfaucet:
    image: chainflag/eth-faucet:1.1.0
    restart: unless-stopped
    container_name: eth_asfaucet
    ports:
      - "18080:8080"
    links:
      - asethereum
    env_file:
      - .env
    command: -wallet.provider http://asethereum:8545 -wallet.privkey ${ALLOC_ADDRESS_PRIVATE_KEY} -faucet.minutes 1
    depends_on:
      - asethereum